# Dependencies
markdown:         redcarpet
pygments:         null

# Permalinks
permalink:        pretty

# Setup
title:            EduGuide Insiders
tagline:          'A Jekyll theme'
description:      'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://eginsiders.github.io

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/EGInsiders/eginsiders.github.io
